# Generated by Django 4.0.5 on 2022-06-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes_ratio', '-votes_total', 'title']},
        ),
    ]
